defaults: &defaults
  adapter: postgresql
  encoding: unicode
  username: tania
  password: password
  host: localhost
  pool: 25

development:
  <<: *defaults
  database: financedatadb_dev

test:
  <<: *defaults
  database: financedatadb_test

production:
  <<: *defaults
  database: financedatadb_prod